// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:voicechat/constants.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Constants.WEB_KEY,
    appId: '1:783953702160:web:6743fce8db64f40d658995',
    messagingSenderId: '783953702160',
    projectId: 'wafasample',
    authDomain: 'wafasample.firebaseapp.com',
    storageBucket: 'wafasample.appspot.com',
    measurementId: 'G-DCJY026124',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Constants.ANDROID_KEY,
    appId: '1:783953702160:android:fa3502e1c81d8821658995',
    messagingSenderId: '783953702160',
    projectId: 'wafasample',
    storageBucket: 'wafasample.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Constants.IOS_KEY,
    appId: '1:783953702160:ios:548b71a780232a91658995',
    messagingSenderId: '783953702160',
    projectId: 'wafasample',
    storageBucket: 'wafasample.appspot.com',
    iosBundleId: 'com.mikirinkode.voicechat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Constants.IOS_KEY,
    appId: '1:783953702160:ios:548b71a780232a91658995',
    messagingSenderId: '783953702160',
    projectId: 'wafasample',
    storageBucket: 'wafasample.appspot.com',
    iosBundleId: 'com.mikirinkode.voicechat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Constants.WINDOWS_KEY,
    appId: '1:783953702160:web:f44ec114b2370d6e658995',
    messagingSenderId: '783953702160',
    projectId: 'wafasample',
    authDomain: 'wafasample.firebaseapp.com',
    storageBucket: 'wafasample.appspot.com',
    measurementId: 'G-HGCYHR2E53',
  );
}
